//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vuz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> Children { get; set; }
        public string GenderId { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string RegistrationtAddress { get; set; }
        public string ActualAddress { get; set; }
        public string Education { get; set; }
        public string Familia { get; set; }
        public string Imya { get; set; }
        public string Otch { get; set; }
        public string FatherFio { get; set; }
        public string FatherJobPlace { get; set; }
        public string FatherJobPosition { get; set; }
        public string MotherFio { get; set; }
        public string MotherJobPlace { get; set; }
        public string MotherJobPosition { get; set; }
        public string FatherTelepthone { get; set; }
        public string MotherTelephone { get; set; }
        public string MotherAdress { get; set; }
        public string FatherAdress { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
